# Use the specified image as base
FROM doubebly/doube-ofiii:1.1.3

# Expose the port used inside the container
EXPOSE 5000

# Default command (optional – if needed to match container behavior)
# CMD ["./start.sh"]
