import json, base64, hashlib, time, re, requests
from urllib.parse import urlencode

class IPTV:
    def __init__(self):
        self.is_proxy = False
        self.proxy = {}
        self.headers = {'User-Agent': 'Mozilla/5.0', 'CLIENT-IP': '127.0.0.1', 'X-FORWARDED-FOR': '127.0.0.1'}
        self.h = ['50.7.92.106', '50.7.220.170', '67.159.6.34', '198.16.100.186', '50.7.234.10']
        self.d = 'W3sidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIummmea4ryIsICJuYW1lIjogIue/oee/oOWPsCIsICJmdW4iOiAic210IiwgInBpZCI6ICJqYWRlX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLpppnmuK8iLCAibmFtZSI6ICLnv6Hnv6Dlj7AgYmFja3VwIiwgImZ1biI6ICJzbXQiLCAicGlkIjogIkphZGVfeHVlIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIummmea4ryIsICJuYW1lIjogImlOZXdzIOaWsOmXu+WPsCIsICJmdW4iOiAic210IiwgInBpZCI6ICJpbmV3c190d24ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi6aaZ5rivIiwgIm5hbWUiOiAiSiAyIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImoyX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLpppnmuK8iLCAibmFtZSI6ICLnj43nj6Dlj7AiLCAiZnVuIjogInNtdCIsICJwaWQiOiAicGVhcmxfdHduIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIummmea4ryIsICJuYW1lIjogIuWHpOWHsOmmmea4ryIsICJmdW4iOiAic210IiwgInBpZCI6ICJoa3Bob2VuaXhfdHduIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIummmea4ryIsICJuYW1lIjogIkhPWei1hOiur+WPsCIsICJmdW4iOiAic210IiwgInBpZCI6ICJob3ljYWlqaW5nX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLpppnmuK8iLCAibmFtZSI6ICJSSEsgMzEiLCAiZnVuIjogInNtdCIsICJwaWQiOiAicmhrMzFfdHduIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIummmea4ryIsICJuYW1lIjogIlZJVVRWMSIsICJmdW4iOiAic210IiwgInBpZCI6ICJ2aXUxX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLpppnmuK8iLCAibmFtZSI6ICJSSEsgMzIiLCAiZnVuIjogInNtdCIsICJwaWQiOiAicmhrMzJfdHduIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIummmea4ryIsICJuYW1lIjogIuWHpOWHsOWNq+inhiIsICJmdW4iOiAic210IiwgInBpZCI6ICJwaG9lbml4dHZfaGQifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi6aaZ5rivIiwgIm5hbWUiOiAi5Yek5Yew6LWE6K6vIiwgImZ1biI6ICJzbXQiLCAicGlkIjogInBob2VuaXhpbmZvX2hkIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIummmea4ryIsICJuYW1lIjogIlZpdTYiLCAiZnVuIjogInNtdCIsICJwaWQiOiAidml1c2l4X3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICJDQ1RWLTEg57u85ZCIIEhEIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImNjdHYxIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS4reWbvSIsICJuYW1lIjogIkNDVFYtMiDotKLnu48iLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY2N0djIifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAiQ0NUVi0zIOe7vOiJuiBIRCIsICJmdW4iOiAic210IiwgInBpZCI6ICJjY3R2MyJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICJDQ1RWLTQg5Lit5paH5Zu96ZmFIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImNjdHY0In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS4reWbvSIsICJuYW1lIjogIkNDVFY0IOaWsOmXu+WPsCIsICJmdW4iOiAic210IiwgInBpZCI6ICJDY3R2NCJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICJDQ1RWLTcg5Yab5LqL5Yac5LiaIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImNjdHY3In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS4reWbvSIsICJuYW1lIjogIkNDVFYtOCDnlLXop4bliacgSEQiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY2N0djhoZCJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICJDQ1RWLTkg6K6w5b2VIEhEIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImNjdHY5aGQifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAiQ0NUVi0xMCDnp5HmlZkgSEQiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY2N0djEwaGQifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAiQ0NUVi0xMSDmiI/mm7IiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY2N0djExIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS4reWbvSIsICJuYW1lIjogIkNDVFYtMTIg56S+5Lya5LiO5rOVIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImNjdHYxMiJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICJDQ1RWLTEzIOaWsOmXu+mikemBkyIsICJmdW4iOiAic210IiwgInBpZCI6ICJjY3R2MTMifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAiQ0NUVi0xNCDlsJHlhL8iLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY2N0djE0In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS4reWbvSIsICJuYW1lIjogIkNDVFYtNiIsICJmdW4iOiAic210IiwgInBpZCI6ICJjY3R2NiJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICJDQ1RWLTE1IOmfs+S5kCIsICJmdW4iOiAic210IiwgInBpZCI6ICJjY3R2MTUifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAi5rmW5Y2X5Y2r6KeGIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImh1bmFuX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICLmtZnmsZ/ljavop4YiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiemhlamlhbmdfdHduIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS4reWbvSIsICJuYW1lIjogIuaxn+iLj+WNq+inhiIsICJmdW4iOiAic210IiwgInBpZCI6ICJqaWFuZ3N1X3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICLmt7HlnLPljavop4YiLCAiZnVuIjogInNtdCIsICJwaWQiOiAic2hlbnpoZW4ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAi56aP5bu65Lic5Y2X5Y2r6KeGIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImZ1amlhbiJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICLlub/kuJzljZfmlrnljavop4YiLCAiZnVuIjogInNtdCIsICJwaWQiOiAibmFuZmFuZ190d24ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAi5bm/5Lic5Y2r6KeGIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImd1YW5nZG9uZ3dlaXNoaV90d24ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAi5YyX5Lqs5Y2r6KeGIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImJlaWppbmcifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAi54+g5rGf5Y+wIiwgImZ1biI6ICJzbXQiLCAicGlkIjogInpodWppYW5nIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS4reWbvSIsICJuYW1lIjogIuW5v+ilv+WNq+inhiIsICJmdW4iOiAic210IiwgInBpZCI6ICJndWFuZ3hpIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS4reWbvSIsICJuYW1lIjogIua5luWMl+WNq+inhiIsICJmdW4iOiAic210IiwgInBpZCI6ICJodWJlaSJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICLlm5vlt53ljavop4YiLCAiZnVuIjogInNtdCIsICJwaWQiOiAic2ljaHVhbl90d24ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAi5Lic5pa55Y2r6KeGIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImRvbmdmYW5nd2Vpc2hpX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICJDR1ROIiwgImZ1biI6ICJzbXQiLCAicGlkIjogIkNHVE4ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAi5Yek5Yew5Y2r6KeGIiwgImZ1biI6ICJzbXQiLCAicGlkIjogInBob2VuaXh0dl9oZCJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICLlh6Tlh7DotYTorq8iLCAiZnVuIjogInNtdCIsICJwaWQiOiAicGhvZW5peGluZm9faGQifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Lit5Zu9IiwgIm5hbWUiOiAiQ0NUVi01IOS9k+iCsumikemBkyIsICJmdW4iOiAic210IiwgInBpZCI6ICJjY3R2NSJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkuK3lm70iLCAibmFtZSI6ICJDQ1RWLTUrIOS9k+iCsui1m+S6iyBIRCIsICJmdW4iOiAic210IiwgInBpZCI6ICJjY3R2NXBsdXMifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiQXN0cm8gUHJlbWllciBMZWFndWUgMSIsICJmdW4iOiAic210IiwgInBpZCI6ICJnb19hc3NwMSJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJBc3RybyBFUEwgMSBiYWNrdXAiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiZ29fYXNzcDF4In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIkFzdHJvIFByZW1pZXIgTGVhZ3VlIDIiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiZ29fYXNzcDIifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiQXN0cm8gR3JhbmRzdGFuZCIsICJmdW4iOiAic210IiwgInBpZCI6ICJnb19hc3NwMyJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJBc3RybyBGb290YmFsbCIsICJmdW4iOiAic210IiwgInBpZCI6ICJnb19hc3NwNCJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJBc3RybyBTcG9ydHMgUGx1cyIsICJmdW4iOiAic210IiwgInBpZCI6ICJnb19zcG9ydHNwbHVzIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIkFzdHJvIEJhZG1pbnRvbiAxIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImdvX2JhZG1pbnRvbjEifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiQXN0cm8gQmFkbWludG9uIDIiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiZ29fYmFkbWludG9uMiJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJBc3RybyBXLVNwb3J0cyIsICJmdW4iOiAic210IiwgInBpZCI6ICJnb19hc3NwNSJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJTdXBlcnNwb3J0cyAxIiwgImZ1biI6ICJzbXQiLCAicGlkIjogIkFzc3AxIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlN1cGVyc3BvcnRzIDIiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiQXNzcDIifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiU3VwZXJzcG9ydHMgMyIsICJmdW4iOiAic210IiwgInBpZCI6ICJBc3NwMyJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJTdXBlcnNwb3J0cyA0IiwgImZ1biI6ICJzbXQiLCAicGlkIjogIkFzc3A0In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIldXRSIsICJmdW4iOiAic210IiwgInBpZCI6ICJXd2UifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiRmlnaHQgU3BvcnRzIiwgImZ1biI6ICJzbXQiLCAicGlkIjogIkZzIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIk5CQSBUViIsICJmdW4iOiAic210IiwgInBpZCI6ICJOYmEifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiQXN0cm8gQ3JpY2tldCIsICJmdW4iOiAic210IiwgInBpZCI6ICJBY3JpY2tldCJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJBc3RybyBHb2xmIiwgImZ1biI6ICJzbXQiLCAicGlkIjogIkFnb2xmIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlRudCBTcG9ydHMgMSIsICJmdW4iOiAic210IiwgInBpZCI6ICI2ZmFjMGFhZWFkIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlROVCBTcG9ydHMgMiIsICJmdW4iOiAic210IiwgInBpZCI6ICJkOWE3NmE3OWNjIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlROVCBTcG9ydHMgMyIsICJmdW4iOiAic210IiwgInBpZCI6ICI1ZmVhNGQ3M2RiIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlROVCBTcG9ydHMgNCIsICJmdW4iOiAic210IiwgInBpZCI6ICJ0bnRzcG9ydDQifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiU29ueSBUZW4gMSIsICJmdW4iOiAic210IiwgInBpZCI6ICJ0ZW4xX3JhaiJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJTb255IFRlbiAyIiwgImZ1biI6ICJzbXQiLCAicGlkIjogInRlbjJfcmFqIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlNvbnkgVGVuIDMiLCAiZnVuIjogInNtdCIsICJwaWQiOiAidGVuM19yYWoifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiU1BPVFYgMSBIRCIsICJmdW4iOiAic210IiwgInBpZCI6ICJnb19zcG90diJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJTUE8gVFYgMiIsICJmdW4iOiAic210IiwgInBpZCI6ICJnb19zcG90djIifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiU2t5c3BvcnRzIEYxIiwgImZ1biI6ICJzbXQiLCAicGlkIjogInRpYW5rb25nZjEifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiU2t5c3BvcnRzIENyaWNrZXQiLCAiZnVuIjogInNtdCIsICJwaWQiOiAidGlhbmtvbmdjcmlja2V0In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlNreXNwb3J0cyBFUEwiLCAiZnVuIjogInNtdCIsICJwaWQiOiAidGlhbmtvbmdlcGwifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiU2t5c3BvcnRzIE1haW4gRXZlbnQiLCAiZnVuIjogInNtdCIsICJwaWQiOiAidGlhbmtvbmdtYWluIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlNreXNwb3J0cyBOZXdzIiwgImZ1biI6ICJzbXQiLCAicGlkIjogInRpYW5rb25nbmV3cyJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJTa3lzcG9ydHMgTWl4IiwgImZ1biI6ICJzbXQiLCAicGlkIjogInRpYW5rb25nbWl4In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIkNDVFYtNSDkvZPogrLpopHpgZMiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY2N0djUifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiQ0NUVi01KyDkvZPogrLotZvkuosgSEQiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY2N0djVwbHVzIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIueIseWwlOi+vuS9k+iCsjLlj7AiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiZWx0YXNwb3J0Ml90d24ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAi54ix5bCU6L6+5L2T6IKyM+WPsCIsICJmdW4iOiAic210IiwgInBpZCI6ICJlbHRhc3BvcnQzX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJSdWdieSBQYXNzIFRWIiwgImZ1biI6ICJzbXQiLCAicGlkIjogIlJ1Z2J5cGFzc3R2In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIlJUTSBTcG9ydHMgSEQiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiUnRtc3BvcnQifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiQXJlbmEiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiQXJlbmEifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiQXJlbmEgMiIsICJmdW4iOiAic210IiwgInBpZCI6ICJBcmVuYTIifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5L2T6IKy6aKR6YGTIiwgIm5hbWUiOiAiQm9sYUFyZW5hIDEiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiQm9sYWFyZW5hMSJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLkvZPogrLpopHpgZMiLCAibmFtZSI6ICJCb2xhQXJlbmEgMiIsICJmdW4iOiAic210IiwgInBpZCI6ICJCb2xhYXJlbmEyIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIkFzdHJvIEJlaW5zcG9ydHMgMSIsICJmdW4iOiAic210IiwgInBpZCI6ICJBc3Ryb2JlaW4xIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIkFzdHJvIEJlaW5zcG9ydHMgMiIsICJmdW4iOiAic210IiwgInBpZCI6ICJBc3Ryb2JlaW4yIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuS9k+iCsumikemBkyIsICJuYW1lIjogIkFzdHJvIEJlaW5zcG9ydHMgMyIsICJmdW4iOiAic210IiwgInBpZCI6ICJBc3Ryb2JlaW4zIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuWPsOa5viIsICJuYW1lIjogIlRWQlMgTmV3cyDmlrDpl7vlj7AiLCAiZnVuIjogInNtdCIsICJwaWQiOiAidHZic19uIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuWPsOa5viIsICJuYW1lIjogIlRWQlMg5qyi5LmQ5Y+wIO+8iOWkh+S7ve+8iSIsICJmdW4iOiAic210IiwgInBpZCI6ICJ0dmJzaHVhbmxlX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICJUVkJTIEhEIiwgImZ1biI6ICJzbXQiLCAicGlkIjogInR2YnMifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Y+w5rm+IiwgIm5hbWUiOiAi5Lit5aSp5paw6Ze7IEhEIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImN0aW5ld3MifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Y+w5rm+IiwgIm5hbWUiOiAi5Lit5aSp5aix5LmQIENUSSBFbnRlcnRhaW1lbnQiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY3RpZW50In0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuWPsOa5viIsICJuYW1lIjogIuS4reWkqee7vOWQiCBDVEkgTWV0cm8iLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY3RpemhvbmdoZSJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLkuK3lpKnkuprmtLLlj7AiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiY3RpYXNpYV90d24ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Y+w5rm+IiwgIm5hbWUiOiAi5Y+w6KeGIFRUViBIRCIsICJmdW4iOiAic210IiwgInBpZCI6ICJ0dHZfdGFpd2FuIn0sIHsidHZnLWlkIjogIiIsICJ0dmctbmFtZSI6ICIiLCAidHZnLWxvZ28iOiAiIiwgImdyb3VwLXRpdGxlIjogIuWPsOa5viIsICJuYW1lIjogIuWPsOinhuaWsOmXu+WPsCIsICJmdW4iOiAic210IiwgInBpZCI6ICJ0dHZuZXdzX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLlj7Dop4bnu7zlkIjlj7AiLCAiZnVuIjogInNtdCIsICJwaWQiOiAidHR2emhvbmdoZSJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLkuK3op4YgSEQiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiemhvbmdzaGloZF90d24ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Y+w5rm+IiwgIm5hbWUiOiAi5Lit6KeG5paw6Ze75Y+wIiwgImZ1biI6ICJzbXQiLCAicGlkIjogInpob25nc2hpbmV3c190d24ifSwgeyJ0dmctaWQiOiAiIiwgInR2Zy1uYW1lIjogIiIsICJ0dmctbG9nbyI6ICIiLCAiZ3JvdXAtdGl0bGUiOiAi5Y+w5rm+IiwgIm5hbWUiOiAi5rCR6KeGIEhEIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImZ0dmhkX3RhaXdhbiJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLmsJHop4bmlrDpl7vlj7AgRlRWIE5ld3MiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiZnR2bmV3X3RhaXdhbiJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLmsJHop4blj7Dmub7lj7AiLCAiZnVuIjogInNtdCIsICJwaWQiOiAiZnR2dGFpd2FuX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLljY7op4YgQ1RTIEhEIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImN0c2hkX3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLlhazop4YgQ1RWIiwgImZ1biI6ICJzbXQiLCAicGlkIjogImN0djE4X3R3biJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLlhavlpKfnrKzkuIAgR1RWIEZpcnN0IiwgImZ1biI6ICJzbXQiLCAicGlkIjogImJhZGFmaXJzdCJ9LCB7InR2Zy1pZCI6ICIiLCAidHZnLW5hbWUiOiAiIiwgInR2Zy1sb2dvIjogIiIsICJncm91cC10aXRsZSI6ICLlj7Dmub4iLCAibmFtZSI6ICLlhavlpKfnu7zlkIggR1RWIE1ldHJvIiwgImZ1biI6ICJzbXQiLCAicGlk'

    def getProxyUrl(self):
        return "/proxy?from=bot"

    def b64decode(self, data):
        return base64.b64decode(data.encode('utf-8')).decode('utf-8')

    def b64encode(self, data):
        return base64.b64encode(data.encode('utf-8')).decode('utf-8')

    def liveContent(self, url):
        data_list = json.loads(self.b64decode(self.d))
        tv_list = ['#EXTM3U']
        for i in data_list:
            tvg_id = i['tvg-id']
            tvg_name = i['tvg-name']
            tvg_logo = i['tvg-logo']
            group_name = i['group-title']
            name = i['name']
            fun = i['fun']
            pid = i['pid']
            tv_list.append(f'#EXTINF:-1 tvg-id="{tvg_id}" tvg-name="{tvg_name}" tvg-logo="{tvg_logo}" group-title="{group_name}",{name}')
            for ip in self.h:
                tv_list.append(f'{self.getProxyUrl()}&fun={fun}&pid={pid}&ip={ip}')
        return '\n'.join(tv_list)
        
    def homeContent(self, filter):
        return {}

    def homeVideoContent(self):
        return {}

    def categoryContent(self, cid, page, filter, ext):
        return {}

    def detailContent(self, did):
        return {}

    def searchContent(self, key, quick, page='1'):
        return {}

    def searchContentPage(self, keywords, quick, page):
        return {}

    def playerContent(self, flag, pid, vipFlags):
        return {}

    def localProxy(self, params):

        _fun = params.get('fun', None)
        _type = params.get('type', None)

        if _fun is not None:
            fun = getattr(self, f'fun_{_fun}')
            return fun(params)

        if _type is not None:
            if params['type'] == "m3u8":
                return self.get_m3u8_text(params)

            if params['type'] == "ts":
                return self.get_ts(params)

        return [302, "text/plain", None, {'Location': 'https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-720p.mp4'}]
    def fun_smt(self, params):
        pid = params['pid']
        ip = params['ip']
        url = f'http://{ip}:8278/{pid}/playlist.m3u8'
        t = str(int(time.time() / 150))
        p = {
            'tid': 'mc42afe745533',
            'ct': t,
            'tsum': hashlib.md5(f'tvata nginx auth module/{pid}/playlist.m3u8mc42afe745533{t}'.encode('utf-8')).hexdigest()
        }
        play_url = self.b64encode(url + '?' + urlencode(p))
        url = f'{self.getProxyUrl()}&type=m3u8&url={play_url}'
        return [302, "text/plain", None, {'Location': url}]


    def get_m3u8_text(self,params):
        url = self.b64decode(params['url'])
        headers = self.headers
        home_url = url.replace(url.split('/')[-1], '')

        def callback_function(match):
            uri = home_url + match.group(1)
            a = self.b64encode(uri)
            # h = params['headers']
            return f"{self.getProxyUrl()}&type=ts&url={a}"
        if self.is_proxy:
            response = requests.get(url, headers=headers, proxies=self.proxy)
        else:
            response = requests.get(url, headers=headers)
        m3u8_text = re.sub(r'(.*\.ts.*)', callback_function, response.text)
        return [200, "application/vnd.apple.mpegurl", m3u8_text]

    def get_ts(self, params):
        url = self.b64decode(params['url'])
        headers = self.headers
        if self.is_proxy:
            response = requests.get(url, headers=headers, proxies=self.proxy)
        else:
            response = requests.get(url, headers=headers)
        return [206, "application/octet-stream", response.content]

    def destroy(self):
        return '正在Destroy'

    def b64encode(self, data):
        return base64.b64encode(data.encode('utf-8')).decode('utf-8')

    def b64decode(self, data):
        return base64.b64decode(data.encode('utf-8')).decode('utf-8')

if __name__ == '__main__':
    pass
